# t-SNE
### (Dimensional Reduction Approach) It only used for visualization purpose

- We get more data points in tail region bcz of that we use t distribution

- It calculates the probability between datapoint in High dimensional subspace and Low dimnesional subspace and Aim is to match these probabilities.

- P(j!i) Probability of i that i record will pick the j record as its neighbor 

- It should match Low dimensional data to Hogh dimensional data. 
- If it is matching then move forward with the data visaulizaton.

- KL Divergence = measure of how different one probability distribution from a second

- Gradient Descent = Change the data point  in Lower dimensional subspace, unless and untill KL values is minimum 

- Gradient Descent = It is keep on changing the values unless and until it will reaches the minium KL values 

- tsne is unsupervised approach
- For PSA and t-SNE is DR approach no need of target column 

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:\Users\sunny\Desktop\DS Material\Data Set\Wine.csv")
df.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [3]:
!pip install bioinfokit

In [4]:
from sklearn.manifold import TSNE
from bioinfokit.visuz import cluster

In [5]:
x = df.iloc[:,:-1]
x

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  
0     3.92     1065  
1     3.40     1050  
2     3.17     1185  
3     3.45     1480  
4     2.93      735  
..     ...      ...  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560  

[178 rows x 13 columns]

In [6]:
tsne = TSNE(n_components=2) 
# n_components is 2 = 2 columns
score = tsne.fit_transform(x)
# fit= will calu=culate the probability, distance 
# transform = will replace the values
score

array([[ 6.08278751e+00,  6.14053345e+00],
       [ 6.34158278e+00,  5.41571951e+00],
       [ 7.87044048e+00,  7.38672495e+00],
       [ 9.93239117e+00,  9.23833656e+00],
       [ 3.86487365e-01, -1.24249138e-01],
       [ 9.61779404e+00,  9.32345009e+00],
       [ 9.08352470e+00,  8.19603443e+00],
       [ 8.69310856e+00,  8.69682980e+00],
       [ 6.25562096e+00,  5.32806969e+00],
       [ 5.82474852e+00,  5.74780130e+00],
       [ 9.94481087e+00,  9.44596767e+00],
       [ 8.51170254e+00,  8.49314690e+00],
       [ 9.25706863e+00,  8.48955536e+00],
       [ 7.48367262e+00,  6.94119740e+00],
       [ 1.00147696e+01,  9.57090569e+00],
       [ 8.93679523e+00,  8.70466805e+00],
       [ 8.92412376e+00,  8.09679794e+00],
       [ 7.15049171e+00,  6.72385406e+00],
       [ 1.01423445e+01,  9.77872658e+00],
       [ 2.59022760e+00,  2.24595356e+00],
       [ 1.36977792e+00,  8.81196320e-01],
       [ 1.29739356e+00,  4.64029789e-01],
       [ 5.68422985e+00,  5.56616306e+00],
       [ 5.

In [9]:
cluster.tsneplot(score, colorlist= df['Customer_Segment'])
# It is saved in current working directory

# Diabities dataset

In [10]:
df1 = pd.read_csv(r"C:\Users\sunny\Desktop\DS Material\Data Set\diabetes.csv")
df1.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
tsne = TSNE(n_components=2)
model = tsne.fit_transform(df1.iloc[:,:-1])
model

array([[  3.3187985, -37.157017 ],
       [  4.861649 , -18.287127 ],
       [ -3.7481916, -45.10908  ],
       ...,
       [  9.203651 ,  25.895136 ],
       [ -9.391772 , -31.785248 ],
       [  5.9387035, -19.762756 ]], dtype=float32)

In [12]:
cluster.tsneplot(model, colorlist= df1['Outcome'])

#  iris  Dataset

In [13]:
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header= None)
df2.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [14]:
tsne = TSNE(n_components=2)
iris = tsne.fit_transform(df2.iloc[:,:-1])
iris


array([[ 10.149618  ,  23.171192  ],
       [  9.234138  ,  20.457317  ],
       [ 10.441611  ,  20.739815  ],
       [ 10.07174   ,  20.245392  ],
       [ 10.399851  ,  23.24962   ],
       [  9.5135355 ,  25.27967   ],
       [ 10.825041  ,  20.960932  ],
       [  9.716958  ,  22.481955  ],
       [ 10.205839  ,  19.494493  ],
       [  9.424741  ,  21.076178  ],
       [ 10.169136  ,  24.646933  ],
       [  9.367702  ,  21.859901  ],
       [  9.543603  ,  20.260895  ],
       [ 10.834516  ,  19.456007  ],
       [ 10.829413  ,  25.72867   ],
       [ 10.331618  ,  26.135948  ],
       [ 10.538406  ,  25.131102  ],
       [  9.944322  ,  23.2304    ],
       [  9.608735  ,  25.64686   ],
       [  9.855076  ,  24.385038  ],
       [  8.904685  ,  24.00914   ],
       [  9.686983  ,  24.042574  ],
       [ 11.58585   ,  21.231117  ],
       [  8.5879    ,  22.87524   ],
       [  8.428366  ,  21.896864  ],
       [  8.785217  ,  20.922226  ],
       [  9.048677  ,  22.738781  ],
 

In [15]:
cluster.tsneplot(iris, colorlist= df2[4], figname= 'iris_data')